# ===================================================================
# NovaInsight Agent Configuration (v3)
# ===================================================================

# -------------------------------------------------------------------
# General & Analysis Settings
# -------------------------------------------------------------------
general:
  debug: false
  log_level: INFO
  supress_user_warnings: true

analysis:
  default_mode: full
  fast_mode_sample_rows: 90

  output:
    default_directory: "."

# -------------------------------------------------------------------
# Cache & Persistence Settings
# -------------------------------------------------------------------
cache:
  enabled: true
  directory_path: "~/.novainsight_cache"

# -------------------------------------------------------------------
# Module Settings (Target Detection, Statistics, etc.)
# -------------------------------------------------------------------
profiler:
  # Warnings from the profiler are triggered based on the violation of those thresholds
  # Dataset level
  duplicate_threshold: 0.10
  dimensionality_threshold: 0.5
  total_memory_threshold: 500
  # Column level
  missing_value_threshold: 0.20
  high_cardinality_threshold: 0.90
  skewness_threshold: 1.0
  memory_hog_threshold: 0.20
  max_categorical_cardinality: 20

target_detection:
  max_categorical_cardinality: 50
  id_uniqueness_threshold: 0.99

statistics:
  outlier_zscore_threshold: 3.0
  multicollinearity_vif_threshold: 10.0
  outlier_warning_threshold: 0.05
  outlier_detection_method: 'mz-score' # 'z-score' | 'mz-score' (modified z-score) 
  spearman_correlation_threshold: 0.85
  cramers_v_correlation_threshold: 0.5
  correlation_ratio_threshold: 0.6
  spearman_leakage_threshold: 0.98
  cramers_v_leakage_threshold: 0.95
  correlation_ratio_leakage_threshold: 0.98
  class_imbalance_threshold: 6.0
  p_value_threshold: 0.05
  bivariate_significance_level: 0.05

dimensionality_reduction:
  imputation_method: 'median' # 'mean' | 'median'
  pca_n_ratios: 10
  tsne_perplexity: 30.0
  tsne_max_iter: 1000
  tsne_learning_rate: 'auto' # 'auto' | float
  umap_n_neighbors: 15
  umap_min_dist: 0.1
  umap_metric: 'euclidean' # 'euclidean' | 'manhattan' | 'cosine'

visualization:
  dpi: 300
  theme: 'whitegrid'
  color_palette: 'mako'
  kmeans_n_clusters: 4
  univariate_countplot_n: 10 # countplot contains top n categories (20 max) 
  bivariate_top_n: -1 # generates bivariate plots for top n features most correlated to target, -1 selects all elligible features

llm:
  provider: google
  model_name: "gemini-1.5-flash-latest"
  temperature: 0.3
  max_tokens: 2048